### ISSUE TITLE
Not working: Rollbar::report_exception($e)

### ISSUE THREAD

**Issue by user11001** [jenssegers/laravel-rollbar#12]
Hi. In previous projects, I liked to use the following syntax for reporting an Exception to Rollbar.

> Rollbar::report_exception($e);

This outputs a lot of meta information (like stacktraces), which can be very useful.

However, this doesn't seem to work well with this package: My Exceptions aren't reported to rollbar.

Any idea how I can fix this?

**Comment by jenssegers** [comment]
If you do `Log::error($exception);`, it will send those stacktraces as well.

**Comment by user11001** [comment]
Works like a charm. Thanks !
