### ISSUE TITLE
Send request info along with errors

### ISSUE THREAD

**Issue by coryvirok** [jenssegers/laravel-rollbar#14]
First off, thanks for building this!

It appears that the request information is not sent along with any errors/logs. I'm not very familiar with Laravel but it seems like you could just add it here: https://github.com/jenssegers/laravel-rollbar/blob/master/src/RollbarLogHandler.php#L79 

It would be very helpful to send over all of the request headers.

**Comment by jenssegers** [comment]
The Rollbar client picks up the request headers.

**Comment by mikebronner** [comment]
Hi Jens,

I have been talking with Cory (from Rollbar) about this -- is there anything I need to configure to have Rollbar pick up the referrer? Using your package with Laravel 5 has not been sending referrers over to Rollbar for some reason.

**Comment by mikebronner** [comment]
Update: OK, my apologies Cory and Jens. I see now where I went wrong. I never realized that the Rollbar occurrence page scrolled to the right to reveal more columns (my resolution somehow made it look like there weren't any more). Scrolling to the right I now see some occurrences have referrers, and some don't. Thanks! (Go ahead and close the issue.)

**Comment by coryvirok** [comment]
Cool. Sorry for the spam and I'm glad it's working. :)
