### ISSUE TITLE
Rollbar not being instantiated on command-line

### ISSUE THREAD

**Issue by phroggyy** [jenssegers/laravel-rollbar#15]
When using `php artisan migrate` and there is an error (I just attempted to migrate with TestDummy without having it installed), we first receive the fatal error `PHP Fatal error:  Class 'Laracasts\TestDummy\Factory' not found in`, then a stack trace, then our symphony `FatalErrorException`
![screen shot 2015-05-28 at 17 22 49](https://cloud.githubusercontent.com/assets/7256451/7863729/3a1af52a-055e-11e5-93a4-52db4a2ab3e4.png)

And then we get, instead of reporting the error to Rollbar, `PHP Fatal error:  Call to a member function report_php_error() on null in /directory/to/repository/vendor/rollbar/rollbar/src/rollbar.php on line 61`.

So how can we pull in Rollbar even for artisan commands? (since the `App` is never loaded)

**Comment by jenssegers** [comment]
This should be fixed now.
