### ISSUE TITLE
Rollbar versioning problems.

### ISSUE THREAD

**Issue by tonglil** [jenssegers/laravel-rollbar#21]
Is using [`~` in composer.json](https://github.com/jenssegers/laravel-rollbar/commit/924277d928d0799a844132f905fee8c6172c0bc0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R15) a good idea?

`~` is the ["next significant release"](https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-) operator, however Rollbar doesn't seems to follow semver and adjust versions that have BC changes in them while using the middle `x.*.x` version number.

I am in the process of upgrading some packages and noticed that Rollbar got upgraded to 0.12.1 and noticed some of my messages are [getting scrubbed](https://github.com/rollbar/rollbar-php/blob/master/CHANGELOG.md#0120).

~0.11 is equivalent to >=0.11 < 1.0.0. If you use ~0.11.0 then it is equivalent to >=0.11.0 < 0.12.0

**Comment by jenssegers** [comment]
Minor releases shouldn't break compatibility. But still waiting for Rollbar to tag a 1.0.0 release though.
