### ISSUE TITLE
Turn off for certain environments.

### ISSUE THREAD

**Issue by tonglil** [jenssegers/laravel-rollbar#22]
How can I disable the provider on an environment basis?

For example, previously I set `rollbar => null` in the services.php config file and it wouldn't try registering it.

Now it throws the error of "access token not configured".

Is there another way to conditionally disable the provider based on environment?

**Comment by GiampaoloFalqui** [comment]
In your services file of your environment configuration folder use this snippet.

For example: ```path/to/your/application/app/config/development/services.php```

```php
    'rollbar' => array(
        'access_token' => $_ENV['ROLLBAR_ACCESS_TOKEN'],
        'level'        => 'none'
    )
```

**Comment by tonglil** [comment]
The thing is, I don't want to give it a key for certain environments because I don't want it to report for those environments.

**Comment by GiampaoloFalqui** [comment]
If you use what I have given you it won't report anything because it doesn't matter what key you use but what level you set.

I use it for my company and it doesn't report anything when I am working on my local environment.

**Comment by tonglil** [comment]
Gotcha, so any random key would work?

**Comment by GiampaoloFalqui** [comment]
I am not sure, but again what matters is the reporting level you set, not the key.

**Comment by jenssegers** [comment]
You could also not load the service provider for development.

**Comment by tonglil** [comment]
Thanks, that works well too!
