### ISSUE TITLE
Uncaught exception 'Mockery\Exception\NoMatchingExpectationException' 

### ISSUE THREAD

**Issue by xroot** [jenssegers/laravel-rollbar#28]
I get this error when I run my tests:

PHP Fatal error:  Uncaught exception 'Mockery\Exception\NoMatchingExpectationException' with message 'No matching handler found for Mockery_0_Illuminate_Config_Repository::get('services.rollbar'). Either the method was unexpected or its arguments matched no expected argument list for this method

Any help guys

**Comment by jenssegers** [comment]
Are you mocking the laravel configuration?
