### ISSUE TITLE
InvalidArgumentException not working

### ISSUE THREAD

**Issue by m4nt4s** [jenssegers/laravel-rollbar#30]
When access_token is not set, than InvalidArgumentException returns nothing instead of "Rollbar token is not set" and then no exeptions are returned.

Would be nice if you could configure, when you can enable or disable rollbar in your project. Maybe if you not set access_token, than exeptions will return normal laravel exceptions and if it's set than rollbar execptions.

**Comment by jenssegers** [comment]
You could also optionally register the service provider for certain environments using `$app->register()`
