### ISSUE TITLE
Ignore some exceptions

### ISSUE THREAD

**Issue by osaris** [jenssegers/laravel-rollbar#32]
Hello,

I have set the ```level``` configuration to ```error``` and also the ```$dontReport``` variable in ```app/Exceptions/Handler.php``` but keep getting error tracking for 404 and wrong CSRF token.

```
	protected $dontReport = [
		'Symfony\Component\HttpKernel\Exception\HttpException',
		'Symfony\Component\HttpKernel\Exception\NotFoundHttpException',
		'Illuminate\Session\TokenMismatchException'
	];
```

Can you help me to avoid reporting those errors ?

Regards

**Comment by jenssegers** [comment]
I'll have a look :)

**Comment by jenssegers** [comment]
Ran tests again for latest version and everything seems to still be ok. The don't report is something implemented by Laravel though, it has nothing to do with the handler.

**Comment by osaris** [comment]
So you put the exact same ```$dontReport``` as me and HttpException, NotFoundHttpException and TokenMismatchException aren't reported ?

**Comment by jenssegers** [comment]
Check out the parent implementation of report. They should use a method called shouldReport (or similar) there. You need to use that as well before you use Log::error

**Comment by osaris** [comment]
@jenssegers thanks, that did the trick.

**Comment by Mastergalen** [comment]
Ah, maybe add that to the **Usage** section of the README?

**Comment by skydiver** [comment]
This was my final code:

```
protected $dontReport = [
    HttpException::class,
    ModelNotFoundException::class,
];
```

```
public function report(Exception $e) {
    if($this->shouldReport($e)) {
        \Log::error($e);
    }
    return parent::report($e);
}
```

**Comment by MladenJanjetovic** [comment]
This should be in installation manual I guess:

public function report(Exception $e) {
    if($this->shouldReport($e)) {
        \Log::error($e);
    }
    return parent::report($e);
}

**Comment by clin407** [comment]
Took me forever to figure this out, stumbled upon this link by the right choice of keywords. Should really add this to the installation guide.
