### ISSUE TITLE
Laravel 4 integration not working after last update

### ISSUE THREAD

**Issue by aspitzer** [jenssegers/laravel-rollbar#34]
After last package update L4.2 integration is not working anymore and is generating WSOD. After remove package everything works again.

**Comment by jenssegers** [comment]
What is the stacktrace? Are you using the current master branch?

**Comment by aspitzer** [comment]
Yes, I'm using master-branch. I will install again and let you know the
stack trace.

Thanks for reply.

Andres

On Tue, Oct 27, 2015 at 11:20 PM, Jens Segers <notifications@github.com>
wrote:

> What is the stacktrace? Are you using the current master branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenssegers/laravel-rollbar/issues/34#issuecomment-151662454>
> .
>



-- 

Andres Spitzer [andres@grupowerk.com]

*Grupo Werk*C/Deia 14
07702 Mahon - Menorca
*tlf.       +34 971 36 72 05*
http://www.grupowerk.com
http://www.facebook.com/grupowerk
http://www.twitter.com/grupowerk
¿Donde estamos?
<http://t.sidekickopen23.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs64kg6YVQZbgl63Rz-KW5v_Sgz56dxhfdWMXsd02?t=http%3A%2F%2Fwww.grupowerk.com%2Fes%2Fcontacto&si=5562082865446912&pi=0e533941-6528-42c3-a15a-cbe27fc9c695>

*CONFIDENCIALIDAD:* La información contenida en este mensaje es
confidencial y para uso exclusivo del destinatario. Si ha recibido este
mensaje por error, le agradeceremos nos lo indique y proceda a su
eliminación.
*CONFIDENTIALITY:* The information contained in this message is
confidential and for the exclusive use of its addressee. If you have
received this message in error, please notify us and delete it from your
system.
*RESPETEMOS EL MEDIO AMBIENTE:* Antes de imprimir este e-mail, piense bien
si es necesario hacerlo. El medio ambiente es cosa de todos.
*PLEASE, RESPECT THE ENVIRONMENT:* Think twice before printing this e-mail.
Environmental protection is in our hands.

**Comment by aspitzer** [comment]
Hello Jen

Here are the details of the error.

After the update I get this error:
Script php artisan clear-compiled handling the post-install-cmd event returned with an error
  [RuntimeException]
  Error Output:
-----

And on php error log I see this error:

[28-Oct-2015 10:11:55 Europe/Madrid] PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::basePath() in /Applications/MAMP/htdocs/evolution/vendor/jenssegers/rollbar/src/RollbarServiceProvider.php on line 42

**Comment by aspitzer** [comment]
I still have same issue after updating with your last commit

**Comment by jenssegers** [comment]
Can you post the stacktrace?

**Comment by aspitzer** [comment]
same as above...

On Wed, Oct 28, 2015 at 9:47 PM, Jens Segers <notifications@github.com>
wrote:

> Can you post the stacktrace?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenssegers/laravel-rollbar/issues/34#issuecomment-151985540>
> .
>



-- 

Andres Spitzer [andres@grupowerk.com]

*Grupo Werk*C/Deia 14
07702 Mahon - Menorca
*tlf.       +34 971 36 72 05*
http://www.grupowerk.com
http://www.facebook.com/grupowerk
http://www.twitter.com/grupowerk
¿Donde estamos?
<http://t.sidekickopen23.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs64kg6YVQZbgl63Rz-KW5v_Sgz56dxhfdWMXsd02?t=http%3A%2F%2Fwww.grupowerk.com%2Fes%2Fcontacto&si=5562082865446912&pi=7b842bd6-706a-493f-8edc-57a75fd1f26d>

*CONFIDENCIALIDAD:* La información contenida en este mensaje es
confidencial y para uso exclusivo del destinatario. Si ha recibido este
mensaje por error, le agradeceremos nos lo indique y proceda a su
eliminación.
*CONFIDENTIALITY:* The information contained in this message is
confidential and for the exclusive use of its addressee. If you have
received this message in error, please notify us and delete it from your
system.
*RESPETEMOS EL MEDIO AMBIENTE:* Antes de imprimir este e-mail, piense bien
si es necesario hacerlo. El medio ambiente es cosa de todos.
*PLEASE, RESPECT THE ENVIRONMENT:* Think twice before printing this e-mail.
Environmental protection is in our hands.
