### ISSUE TITLE
Turn off on development

### ISSUE THREAD

**Issue by kayyyy** [jenssegers/laravel-rollbar#43]
Hi,

first thanks for this package, good work :+1: 

Could you tell me how i can disable this package / notifications on my local development?

**Comment by pedrommone** [comment]
Here you go. In *exceptions/Handler.php*

```php
    public function report(Exception $e)
    {
        if (App::environment('production')) {
            Log::error($e);
        }

        return parent::report($e);
    }
```

**Comment by pedrommone** [comment]
Here you go. In **exceptions/Handler.php**

```php
    public function report(Exception $e)
    {
        if (App::environment('production')) {
            Log::error($e);
        }

        return parent::report($e);
    }
```

**Comment by kayyyy** [comment]
@pedrommone Awesome, thank you :+1:

**Comment by mbardelmeijer** [comment]
@pedrommone this doesn't work for fatal errors due to the `register_shutdown_function` call in the serviceprovider. What do you recommend for disabling that as well in development?

**Comment by pedrommone** [comment]
@mbardelmeijer we're noticied that too, currently I have no tip for you :(

**Comment by edbentinck** [comment]
@pedrommone Just out of curiosity, what's the difference with your code snippet when [the parent Handler logs errors anyway](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Exceptions/Handler.php#L53-L58)? Perhaps I'm missing something?

**Comment by pedrommone** [comment]
@edbentinck sorry for delay. We change this piece of code when I noticed it as well! :) now is something like this

```php
    public function report(Exception $e)
    {
        if (App::environment('production')) {
            Log::error($e);
            return parent::report($e);
        }
    }
```
