### ISSUE TITLE
Detect Environment

### ISSUE THREAD

**Issue by mydnic** [jenssegers/laravel-rollbar#47]
Hello,
Is it possible to add something in the configuration file that allows to only send errors to rollbar on certain environment ? Like, I don't necessary need to log errors to rollbar when I am working in local. Only in Staging and production for example.

Before I was using a simple if (env('APP_ENV') != 'local') to trigger the rollbar report, but since Laravel 5.2 it seems that doesn't work anymore :(

Many thanks

**Comment by pedrommone** [comment]
I guess its related to #43

**Comment by mydnic** [comment]
seems to work with the solution provided in #43 !
the return just has to be in the if condition as well
thanks a lot
