### ISSUE TITLE
Disabling Rollbar for local and testing environments

### ISSUE THREAD

**Issue by alariva** [jenssegers/laravel-rollbar#51]
Since `laravel-rollbar` throws an Exception if no access token is set, I'm not sure about the way to disable it for local testing.

Is there a suggested way to configure no ACCESS_TOKEN for testing/continuous integration environments?

I'm currently adding this to register() at AppServiceProvider.php

    if ($this->app->environment() != 'testing') {
        $this->app->register(Jenssegers\Rollbar\RollbarServiceProvider::class);
    }

But unsure about if it's the best way.

Thanks in advance!

**Comment by jenssegers** [comment]
I'm doing that as well. Probably best to add it to the readme :)

**Comment by jenssegers** [comment]
Updated readme!
