### ISSUE TITLE
Sending messages on level none

### ISSUE THREAD

**Issue by borislavgit** [jenssegers/laravel-rollbar#53]
Hey, I'm a big fan of rollbar and I want to say how happy I am to be using the Laravel wrapper you've provided :)

One question though - I've configured the level to none but error messages are still sent to rollbar. :( Is this how it's supposed to work or is it a bug only on my end?

Thanks

**Comment by borislavgit** [comment]
Never mind, it was on my end. :)

**Comment by omer414** [comment]
I am also having issues with this. Laravel keeps sending messages even when i have none as the level.
Do you mind sharing what was the problem at your end?
