### ISSUE TITLE
rollbar-php 0.18, checkIgnore fatal error

### ISSUE THREAD

**Issue by mseymour** [jenssegers/laravel-rollbar#57]
When I try to use the new checkIgnore functionality for rollbar-php (https://rollbar.com/docs/notifier/rollbar-php/#configuration-reference), I get a fatal error:

    Fatal error: Uncaught ReflectionException: Class log does not exist in /Users/mark/Sites/[...]/vendor/laravel/framework/src/Illuminate/Container/Container.php:734

    Stack trace: 
    #0 /Users/mark/Sites/[...]/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log') 
    #1 /Users/mark/Sites/[...]/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array) 
    #2 /Users/mark/Sites/[...]/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array) 
    #3 /Users/mark/Sites/[...]/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(49): Illuminate\Foundation\Application->make('log') 
    #4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application)) 
    #5 /Users/mark/Sites/[...]/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass- in /Users/mark/Sites/[...]/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734

**Comment by mseymour** [comment]
And I did change the exception handler back to default, which results in the same issue.

**Comment by loweoj** [comment]
This package is using rollbar version 0.15. I guess the feature you're trying to use was added since. 

@jenssegers Can we get rollbar updated to latest version? Or will this break things?

**Comment by loweoj** [comment]
Have you `composer update` in your project to pull in latest version of rollbar?

**Comment by mseymour** [comment]
Oh. I did, turned out there was a small syntax error that I missed. Weird that a syntax error would cause that message though.
