### ISSUE TITLE
Only in production environment

### ISSUE THREAD

**Issue by gabrielbuzziv** [jenssegers/laravel-rollbar#75]
How can i enable the Rollbar only for production mod, i don't want to be spammed in my emaisl while my ap is locally.

**Comment by drbyte** [comment]
The answer to that is in the README ...

> If you only want to enable Rollbar reporting for certain environments you can conditionally load the service provider in your AppServiceProvider:

```php
if ($this->app->environment('production')) {
    $this->app->register(\Jenssegers\Rollbar\RollbarServiceProvider::class);
}```

**Comment by gabrielbuzziv** [comment]
Ops, sorry didn't see
