### ISSUE TITLE
Capacity to override default person without resorting to context in every log statement

### ISSUE THREAD

**Issue by paulrrogers** [jenssegers/laravel-rollbar#82]
There does not appear to be any way to set the signed-in person's details (ID, username, etc.) without explicitly doing so with every log statement. Am I missing something?

**Comment by squatto** [comment]
In your config you can set `person_fn` to `Auth::user` (or any function that returns the user). For example:

`
'rollbar' => [
    'access_token' => env('ROLLBAR_TOKEN'),
    'level' => env('ROLLBAR_LEVEL'),
    'person_fn' => 'Auth::user',
],
`
