### ISSUE TITLE
Cannot get this to function in Laravel 5.0.17

### ISSUE THREAD

**Issue by olimorris** [jenssegers/laravel-rollbar#9]
Hi,

For whatever reason, I just cannot get this to send any information to Rollbar in either production or local environments. No errors are shown with regards to installation. I can log errors just fine to my Laravel log  file however I just cannot seem to send any data over to Rollbar.

Has this been tested with 5.0.17?

**Comment by lowerends** [comment]
You need to add a line in your exception handler (```app/Exceptions/Handler.php```):

````
public function report(Exception $e)
{
	\Log::error($e);

	return parent::report($e);
}
````

**Comment by xitude** [comment]
I had the same issue, the above comment fixed it.

**Comment by olimorris** [comment]
Agreed this is the solution. Worth adding this to your readme as countless other people may be experiencing this. Conversely Bugsnag worked first time...

**Comment by jenssegers** [comment]
I updated the installation instructions to be more clear.
