### ISSUE TITLE
Update rollbar-php

### ISSUE THREAD

**Issue by mehrdad-shokri** [jenssegers/laravel-rollbar#92]
Hey, rollbar-php ``1.2.0`` is released now, this library uses version ``0.18.2``.  
Any plan to update code base?

**Comment by wjgilmore** [comment]
Would also love to know if there is any specific reason this package is using such an old version of the Rollbar library. Any particular technical reasons why?

**Comment by waqas-mehmood-pk** [comment]
+1

**Comment by jnbn** [comment]
Did anybody manage to update and try it properly on local environment?  @mehrdaad @wjgilmore @whfamily2006

**Comment by jnbn** [comment]
You can use https://github.com/rollbar/rollbar-php-laravel

**Comment by mehrdad-shokri** [comment]
@jnbn ok thnx.
